Rendering Example
#################

`embed:skinName` Skin
*********************

This specification shows the different outputs generated by the `embed:skinName` [Fancordion Skin]`afFancordion::Skin`.

When a command is successful it is shown in [Green]`eq:"Green"`.

When a command fails it is shown in [Green]`eq:"Red"`.

Sometimes the unexpected happens and a command throws an [Exception]`exe:throw Err("Boom! In yer face!")`



Example: Tables
---------------
Fancordion allows a simple table markup to be used in the specifications. 
Tables may be used to run the same command over multiple rows of data: 

  table:
  col[2]+eq:((#COL[0] == "Britt") ? "Nina Hartley" : #COL[0] + " " + #COL[1])

  First Name   Last Name   Full Name
  ----------   ---------   --------------
  Joanna       Storm       Joanna Storm
  Rachel       Ashley      Rachel Ashley
  Amber        Lynn        Amber Lynn
  Barbara      Dare        Barbara Dare
  Britt        Morgan      Britt Morgan



Example: Pre Text
----------------
Pre-formatted text is useful for showing:

  System messages and verbatim text

It may also be used for verifications:

  eq:"Green for success!"
  Green for success!